# Numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])

In [4]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [9]:
mat1=np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
mat1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
mat1.shape

(2, 4)

In [13]:
arr1.shape

(6,)

In [14]:
mat1.dtype

dtype('int32')

In [16]:
mat1[0,0] = 10

In [17]:
mat1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [19]:
mat1[0,0]="String value"

ValueError: invalid literal for int() with base 10: 'String value'

In [20]:
mat2 = np.arange(0,20, 1)
mat2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
mat3 = np.linspace(0,10,20)
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
mat3.shape

(20,)

In [25]:
mat4= np.random.rand(5,5)
mat4

array([[0.31083321, 0.50297779, 0.01711418, 0.43646352, 0.94173488],
       [0.24515712, 0.99779191, 0.69568701, 0.07205813, 0.27712731],
       [0.62839012, 0.30141668, 0.35946447, 0.71660928, 0.8904345 ],
       [0.87830849, 0.84452457, 0.97579923, 0.78264158, 0.27159111],
       [0.39014588, 0.64580776, 0.51284247, 0.76643958, 0.67184917]])

In [26]:
mat4.shape # all the values lies between 0 to 1

(5, 5)

In [27]:
mat5 = np.random.randn(5,5)
mat5    # All random values 

array([[-0.3203049 ,  1.50938321, -1.48438236,  0.73262099,  0.35149302],
       [ 0.53112621,  0.55524949,  0.64028785, -0.54979647, -1.31266351],
       [ 1.53444051,  1.35958793,  0.34565884, -0.43799138, -0.86315964],
       [ 0.53502877, -0.07307592, -0.1632666 , -1.09110941,  0.67169669],
       [ 0.89708954,  0.85707828, -0.24842074, -0.3120262 , -1.08911648]])

In [28]:
mat5[0,0]

-0.3203049000311638

In [29]:
mat5[0:4, 0:3] # first 4 (index b/w 0 to 3)row and 3(index b/w 0 to 2) columns

array([[-0.3203049 ,  1.50938321, -1.48438236],
       [ 0.53112621,  0.55524949,  0.64028785],
       [ 1.53444051,  1.35958793,  0.34565884],
       [ 0.53502877, -0.07307592, -0.1632666 ]])